# Generated by Django 3.2.3 on 2021-05-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contato',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
